spring:
  application:
    name: SpringBootBase
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:postgresql://localhost:5432/cb
    username: root
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 1000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    display-request-duration: true

logging:
  level:
    com.hsryuuu: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    feign.Logger: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.cors: TRACE
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.access: DEBUG
    org.springframework.security.web.access.intercept: DEBUG
    org.springframework.transaction: DEBUG

kakao:
  api_key: c9d632cf272516130994271caf59f118 # kakao api key
  redirect_uri: http://localhost:8080/kakao/redirect-uri