spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
